# This is a basic workflow to help you get started with Actions

name: Build LaTeX document

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches
  push:
  # Triggers the workflow on pull requests for all branches
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_latex"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      # 2. Build the Latex document
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "aktuell/*.tex"
          glob_root_file: true
          work_in_root_file_dir: true
          
          #args: "--shell-escape -lualatex -file-line-error -halt-on-error -interaction=nonstopmode"
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          
          # update LaTeX-Packages (this takes a long time, so we avoid it if possible)
          #pre_compile: "tlmgr update --self && tlmgr update --all"
          # Cleanup
          post_compile: "latexmk -c"
        env:
          # Include Shared Folder
          #TEXINPUTS: ".:../shared:../shared/paket//:"
      # 3. Copy the generated pdf to the output folder
      - name: Copy generated pdf to output folder
        run: "cp aktuell/*.pdf ."
      # 8. Upload artifacts to GitHub
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
